# Generated by Django 4.2.9 on 2024-02-01 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groups',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='groups',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
