# Generated by Django 4.2.9 on 2024-02-01 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_groups_created_at_groups_name_groups_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertising',
            options={'verbose_name': 'Reklamma', 'verbose_name_plural': 'Reklammalar'},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': "Sms jo'natiladigan guruh", 'verbose_name_plural': "Sms jo'natiladigan guruhlar"},
        ),
    ]
